CXX = g++
CXXFLAGS = -std=c++17 -Wall

SRC = src/main.cpp src/CustomerBase.cpp src/RegularCustomer.cpp src/VipCustomer.cpp src/Hotel.cpp
OUT = hotel

all:
	$(CXX) $(CXXFLAGS) $(SRC) -o $(OUT)

clean:
	rm -f $(OUT)

